### ISSUE TITLE
Upgrade to get-port 6.x.x

### ISSUE THREAD

**Issue by jleni** [Zondax/zemu#123]

**Comment by jleni** [comment]
The dependabot open PR triggers an incompatibility

**Comment by carlosala** [comment]
We can't do this because we are using a compiled typescript code of `commonjs` kind, that is incompatible with new versions of get-port. We should switch to `esnext` for example to be able to do this. And obviously stop using `require`, always `import`.

**Comment by carlosala** [comment]
Closing here, updating to get-port >5 would require a change in the typescript compilation phase. `get-port` 5 is enough for the moment.
