### ISSUE TITLE
Set private members in Zemu class as protected?

### ISSUE THREAD

**Issue by overcat** [Zondax/zemu#162]
In some cases, we may want to modify some behaviors in Zemu, but some functions and members in Zemu classes are set to private, can we modify them to protected?

:link: [zboto Link](https://app.clickup.com/t/2vxjnru)

**Comment by carlosala** [comment]
We might consider that, for sure! Could you please specify which are the properties/methods that should be changed to fit your actual needs?
Thanks!

**Comment by overcat** [comment]
Thanks for your response, what I want to modify is [click method](https://github.com/Zondax/zemu/blob/7fbd43608f/src/index.ts#L616), but it uses `speculosApiPort` inside, and `speculosApiPort` is private, so it is enough for me to just change `speculosApiPort` to **protected**.

**Comment by carlosala** [comment]
New version released, with `speculosApiPort` protected! https://github.com/Zondax/zemu/releases/tag/v0.33.1

**Comment by overcat** [comment]
Thank you, it works well.
