### ISSUE TITLE
Can we detect if the .elf is nano s or nano x ?

### ISSUE THREAD

**Issue by rllola** [Zondax/zemu#45]
If we can detect if it is one or the other we could void the horrible crash when we load nano x in a nano s emulator and show a more informational error message.

**Comment by TamtamHero** [comment]
Using `readelf -h bin/app.elf`, you can fetch the entry point address which is different on S/X:
On nano S: 
`Entry point address:               0xc0d00001`
On nano X:
`Entry point address:               0xc0de0001`

I don't know if it's the best way to discriminate, but it's a start. Some logic could be added in speculos to remove the `--model` arg.

**Comment by jleni** [comment]
Beautiful! We can definitely add that to Zemu.. so model selection is automatic

**Comment by rllola** [comment]
I don't think automatic selection is a good thing. If it is going to be smart, it is going to do things that I don't understand.

I believe that just making a simple check is useful enough. Also a good documentation.

**Comment by jleni** [comment]
Yes, makes sense.. we can keep it on the safe side and we can confirm that we are testing the intended app/model.
Nice work!
