### ISSUE TITLE
Add `navigate` method without comparing screenshots

### ISSUE THREAD

**Issue by becominginsane** [Zondax/zemu#81]
This would allow us to navigate with the same friendly and easy to use API as the normal `navigateAndCompareSnapshots` without having to compare snapshots or relying on for loops

Ideally, the method would also take the sequence of movements as parameters, like the 3rd argument of `navigateAndCompareSnapshots`

**Comment by ftheirs** [comment]
This was my first thought! Maybe both features can be added together.
Related to: https://github.com/Zondax/zemu/issues/142
