### ISSUE TITLE
Add ability to search for specific screen

### ISSUE THREAD

**Issue by becominginsane** [Zondax/zemu#82]
We currently have `waitUntilScreenIsNot` which does a fantastic job in allowing us to wait until an application is starting to show something on screen, but it would be useful for some use cases to be able to navigate thru the app in search for a specific screen (with a timeout) so that we can more easily seek to a screen we are trying to inspect, regardless of the number of screens needed to scroll towards the destination.

A simple example is a way to accept all prompts shown on the screen, by looking for the "accept" screen, and then simply clicking both buttons, without having to navigate X screens, possibly not being enough screens if the prompt needs to show a large number of pages

**Comment by neithanmo** [comment]
I think #93 and #102 close this issue.. @ftheirs?

**Comment by becominginsane** [comment]
#102 Only makes the first screen searchable by text, but a method to search for a given screen is still lacking, unless I'm missing something?

**Comment by neithanmo** [comment]
> #102 Only makes the first screen searchable by text, but a method to search for a given screen is still lacking, unless I'm missing something?

#109 adds a function to navigate and compare snapshots until a certain screen is found. So it is probably what you mean right?

**Comment by becominginsane** [comment]
Well somewhat, but from my understanding doesn't it require to have all intermediary screenshots as well? The point of the request was to make this kind of search be able to be fast, not slower (by comparing each screenshot)

**Comment by becominginsane** [comment]
I looked over the code again and now I understand, I thought it was comparing the screenshot each time but I now see that it's comparing only the last screenshot instead.
